[package]
name = "llrt_http"
description = "LLRT Module http"
version = "0.3.0-beta"
edition = "2021"
license = "Apache-2.0"
repository = "https://github.com/awslabs/llrt"
readme = "README.md"

[lib]
name = "llrt_http"
path = "src/lib.rs"

[features]
default = ["http1", "http2"]

http1 = ["hyper/http1", "hyper-rustls/http1"]
http2 = ["hyper/http2", "hyper-rustls/http2"]

[dependencies]
brotlic = "0.8"
bytes = "1.6.1"
flate2 = { version = "1", features = ["zlib-ng"], default-features = false }
http-body-util = "0.1.2"
hyper = { version = "1.4.1", features = ["client"] }
hyper-rustls = { version = "0.27.2", default-features = false, features = [
  "webpki-roots",
  "webpki-tokio",
  "ring",
] }
hyper-util = "0.1.6"
itoa = "1"
llrt_abort = { version = "0.3.0-beta", path = "../llrt_abort" }
llrt_json = { version = "0.3.0-beta", path = "../llrt_json" }
llrt_utils = { version = "0.3.0-beta", path = "../../libs/llrt_utils", features = [
  "encoding",
], default-features = false }
pin-project-lite = "0.2"
once_cell = "1"
rquickjs = { git = "https://github.com/DelSkayn/rquickjs.git", rev = "3af3f46b13eb89a2694e5e4e2e73924a20fa9dd1", default-features = false }
rustls = { version = "0.23.11", default-features = false, features = [
  "tls12",
  "ring",
] }
ryu = "1.0.18"
tokio = "1"
tracing = "0.1"
webpki-roots = "0.26.3"
zstd = { version = "0.13.2", default-features = false }

[dev-dependencies]
llrt_test = { path = "../../libs/llrt_test" }
tokio = { version = "1", features = ["full"] }
wiremock = "0.6.0"
