[package]
name = "llrt_http"
description = "LLRT Module http"
version = "0.3.0-beta"
edition = "2021"
license = "Apache-2.0"
repository = "https://github.com/awslabs/llrt"
readme = "README.md"

[lib]
name = "llrt_http"
path = "src/lib.rs"

[features]
default = ["http1", "http2", "compression-c"]

http1 = ["hyper/http1", "hyper-rustls/http1"]
http2 = ["hyper/http2", "hyper-rustls/http2"]

compression-c = ["llrt_compression/all-c"]
compression-rust = ["llrt_compression/all-rust"]

[dependencies]
bytes = "1"
either = "1"
http-body-util = "0.1"
hyper = { version = "1", features = ["client"] }
hyper-rustls = { version = "0.27", default-features = false, features = [
  "webpki-roots",
  "webpki-tokio",
  "ring",
] }
hyper-util = "0.1"
itoa = "1"
llrt_abort = { version = "0.3.0-beta", path = "../llrt_abort" }
llrt_compression = { version = "0.3.0-beta", path = "../../libs/llrt_compression", default-features = false }
llrt_context = { version = "0.3.0-beta", path = "../../libs/llrt_context" }
llrt_encoding = { version = "0.3.0-beta", path = "../../libs/llrt_encoding" }
llrt_json = { version = "0.3.0-beta", path = "../../libs/llrt_json" }
llrt_url = { version = "0.3.0-beta", path = "../llrt_url" }
llrt_utils = { version = "0.3.0-beta", path = "../../libs/llrt_utils", default-features = false }
pin-project-lite = "0.2"
once_cell = "1"
rquickjs = { git = "https://github.com/DelSkayn/rquickjs.git", rev = "2627859ac65c714e35d3232fa8c59b40668cfa7e", features = [
  "either",
], default-features = false }
rustls = { version = "0.23", default-features = false, features = [
  "tls12",
  "ring",
] }
ryu = "1"
tokio = "1"
tracing = "0.1"
webpki-roots = "0.26"

[dev-dependencies]
llrt_compression = { version = "0.3.0-beta", path = "../../libs/llrt_compression" }
llrt_test = { path = "../../libs/llrt_test" }
tokio = { version = "1", features = ["full"] }
wiremock = "0.6"
