[package]
name = "llrt"
version = "0.2.0-beta"
edition = "2021"
license-file = "LICENSE"

[features]
default = ["macro"]
macro = ["llrt_core/macro"]
lambda = ["llrt_core/lambda"]
no-sdk = ["llrt_core/no-sdk"]
uncompressed = ["llrt_core/uncompressed"]

[dependencies]
llrt_core = { path = "../llrt_core" }
tracing = { version = "0.1.40", features = ["log"] }
chrono = { version = "0.4.38", default-features = false, features = ["std"] }
tracing-core = "0.1.32"
tokio = { version = "1", features = ["full"] }

[target.'cfg(not(target_os = "windows"))'.dependencies]
snmalloc-rs = { version = "0.3.6", features = ["lto"] }

[target.'cfg(target_os = "windows")'.dependencies]
mimalloc = { version = "0.1.43" }

[[bin]]
name = "llrt"
path = "src/main.rs"
