[package]
name = "llrt_perf_hooks"
description = "LLRT Module perf_hooks"
version = "0.8.0-beta"
edition = "2021"
license = "Apache-2.0"
repository = "https://github.com/awslabs/llrt"
readme = "README.md"

[lib]
name = "llrt_perf_hooks"
path = "src/lib.rs"

[dependencies]
llrt_events = { version = "0.8.0-beta", path = "../llrt_events" }
llrt_utils = { version = "0.8.0-beta", path = "../../libs/llrt_utils", default-features = false }
rquickjs = { version = "0.11", default-features = false }

[dev-dependencies]
llrt_test = { path = "../../libs/llrt_test" }
