[package]
name = "llrt_timezone"
description = "LLRT Module timezone"
version = "0.7.0-beta"
edition = "2021"
license = "Apache-2.0"
repository = "https://github.com/awslabs/llrt"
readme = "README.md"

[lib]
name = "llrt_timezone"
path = "src/lib.rs"

[dependencies]
chrono = { version = "0.4", features = ["std", "clock"], default-features = false }
chrono-tz = { version = "0.10", default-features = false }
iana-time-zone = "0.1"
rquickjs = { git = "https://github.com/DelSkayn/rquickjs.git", version = "0.10.0", default-features = false }
llrt_utils = { version = "0.7.0-beta", path = "../../libs/llrt_utils" }
