[package]
name = "llrt_util"
description = "LLRT Module util"
version = "0.8.1-beta"
edition = "2021"
license = "Apache-2.0"
repository = "https://github.com/awslabs/llrt"
readme = "README.md"

[lib]
name = "llrt_util"
path = "src/lib.rs"

[dependencies]
llrt_context = { version = "0.8.1-beta", path = "../../libs/llrt_context" }
llrt_encoding = { version = "0.8.1-beta", path = "../../libs/llrt_encoding" }
llrt_logging = { version = "0.8.1-beta", path = "../../libs/llrt_logging" }
llrt_utils = { version = "0.8.1-beta", path = "../../libs/llrt_utils", default-features = false }
rquickjs = { version = "0.11", default-features = false }
