[package]
name = "llrt_string_decoder"
description = "LLRT Module string_decoder"
version = "0.8.1-beta"
edition = "2021"
license = "Apache-2.0"
repository = "https://github.com/awslabs/llrt"
readme = "README.md"

[lib]
name = "llrt_string_decoder"
path = "src/lib.rs"

[dependencies]
llrt_buffer = { version = "0.8.1-beta", path = "../llrt_buffer" }
llrt_encoding = { version = "0.8.1-beta", path = "../../libs/llrt_encoding" }
llrt_utils = { version = "0.8.1-beta", path = "../../libs/llrt_utils", default-features = false }
rquickjs = { version = "0.11", default-features = false }

[dev-dependencies]
llrt_test = { path = "../../libs/llrt_test" }
tokio = { version = "1", features = ["test-util"], default-features = false }
