[package]
name = "llrt_net"
description = "LLRT Module net"
version = "0.3.0-beta"
edition = "2021"
license = "Apache-2.0"
repository = "https://github.com/awslabs/llrt"
readme = "README.md"

[lib]
name = "llrt_net"
path = "src/lib.rs"

[dependencies]
itoa = "1"
llrt_buffer = { version = "0.3.0-beta", path = "../llrt_buffer" }
llrt_events = { version = "0.3.0-beta", path = "../llrt_events" }
llrt_stream = { version = "0.3.0-beta", path = "../llrt_stream" }
llrt_utils = { version = "0.3.0-beta", path = "../../llrt_utils", default-features = false }
rquickjs = { git = "https://github.com/DelSkayn/rquickjs.git", rev = "3af3f46b13eb89a2694e5e4e2e73924a20fa9dd1", default-features = false }
tokio = { version = "1", features = ["net"] }
tracing = "0.1"

[dev-dependencies]
llrt_test = { path = "../../llrt_test" }
rand = "0.8"
tokio = { version = "1", features = ["full"] }
