[package]
name = "llrt_url"
description = "LLRT Module url"
version = "0.5.1-beta"
edition = "2021"
license = "Apache-2.0"
repository = "https://github.com/awslabs/llrt"
readme = "README.md"

[lib]
name = "llrt_url"
path = "src/lib.rs"

[dependencies]
llrt_utils = { version = "0.5.1-beta", path = "../../libs/llrt_utils", default-features = false }
rquickjs = { git = "https://github.com/DelSkayn/rquickjs.git", version = "0.9.0", features = [
  "macro",
], default-features = false }
url = "2.5"

[dev-dependencies]
llrt_test = { path = "../../helpers/llrt_test" }
tokio = { version = "1", features = ["full"] }
