[package]
name = "llrt_url"
description = "LLRT Module url"
version = "0.7.0-beta"
edition = "2021"
license = "Apache-2.0"
repository = "https://github.com/awslabs/llrt"
readme = "README.md"

[lib]
name = "llrt_url"
path = "src/lib.rs"

[dependencies]
llrt_utils = { version = "0.7.0-beta", path = "../../libs/llrt_utils", default-features = false }
rquickjs = { version = "0.11", default-features = false }
url = { version = "2", features = ["std"], default-features = false }

[dev-dependencies]
llrt_test = { path = "../../libs/llrt_test" }
tokio = { version = "1", features = ["test-util"], default-features = false }
