[package]
name = "llrt_timers"
description = "LLRT Module timers"
version = "0.3.0-beta"
edition = "2021"
license = "Apache-2.0"
repository = "https://github.com/awslabs/llrt"

[lib]
name = "llrt_timers"
path = "src/lib.rs"

[dependencies]
llrt_utils = { version = "0.3.0-beta", path = "../../llrt_utils", features = [
  "ctx",
], default-features = false }
once_cell = "1"
rquickjs = { git = "https://github.com/DelSkayn/rquickjs.git", rev = "3af3f46b13eb89a2694e5e4e2e73924a20fa9dd1", default-features = false }
tokio = { version = "1", features = ["sync", "time", "macros"] }

[dev-dependencies]
llrt_test = { path = "../../llrt_test" }
tokio = { version = "1", features = ["full"] }
