[package]
name = "llrt_timers"
description = "LLRT Module timers"
version = "0.6.0-beta"
edition = "2021"
license = "Apache-2.0"
repository = "https://github.com/awslabs/llrt"

[lib]
name = "llrt_timers"
path = "src/lib.rs"

[dependencies]
llrt_context = { version = "0.6.0-beta", path = "../../libs/llrt_context" }
llrt_utils = { version = "0.6.0-beta", path = "../../libs/llrt_utils", default-features = false }
once_cell = { version = "1", features = [
  "std",
], default-features = false }
rquickjs = { git = "https://github.com/DelSkayn/rquickjs.git", version = "0.9.0", default-features = false }
tokio = { version = "1", features = [
  "macros",
  "sync",
  "time",
], default-features = false }

[dev-dependencies]
llrt_test = { path = "../../libs/llrt_test" }
