[package]
name = "llrt_stream"
description = "LLRT Module stream"
version = "0.3.0-beta"
edition = "2021"
license = "Apache-2.0"
repository = "https://github.com/awslabs/llrt"

[lib]
name = "llrt_stream"
path = "src/lib.rs"

[dependencies]
llrt_buffer = { version = "0.3.0-beta", path = "../llrt_buffer" }
llrt_context = { version = "0.3.0-beta", path = "../../libs/llrt_context" }
llrt_events = { version = "0.3.0-beta", path = "../llrt_events" }
llrt_utils = { version = "0.3.0-beta", path = "../../libs/llrt_utils", features = [
  "bytearray-buffer",
], default-features = false }
rquickjs = { git = "https://github.com/DelSkayn/rquickjs.git", rev = "3af3f46b13eb89a2694e5e4e2e73924a20fa9dd1", default-features = false }
tokio = { version = "1", features = ["macros", "io-util"] }
