[package]
name = "llrt_navigator"
description = "LLRT Module navigator"
version = "0.8.1-beta"
edition = "2021"
license = "Apache-2.0"
repository = "https://github.com/awslabs/llrt"
readme = "README.md"

[lib]
name = "llrt_navigator"
path = "src/lib.rs"

[dependencies]
rquickjs = { version = "0.11", default-features = false }
