[package]
name = "llrt_intl"
description = "LLRT Intl module - minimal internationalization support"
version = "0.8.1-beta"
edition = "2021"
license = "Apache-2.0"
repository = "https://github.com/awslabs/llrt"
readme = "README.md"

[lib]
name = "llrt_intl"
path = "src/lib.rs"

[dependencies]
itoa = "1.0"
jiff = { version = "0.2" }
rquickjs = { version = "0.11", default-features = false }
llrt_utils = { version = "0.8.1-beta", path = "../../libs/llrt_utils" }
