[package]
name = "llrt_crypto"
description = "LLRT Module crypto"
version = "0.5.1-beta"
edition = "2021"
license = "Apache-2.0"
repository = "https://github.com/awslabs/llrt"
readme = "README.md"

[lib]
name = "llrt_crypto"
path = "src/lib.rs"

[features]
default = ["subtle-rs"]

subtle-rs = [
  "llrt_json",
  "aes",
  "aes-gcm",
  "aes-kw",
  "cbc",
  "ctr",
  "rsa",
  "p256",
  "p384",
  "p521",
  "elliptic-curve",
  "x25519-dalek",
  "ecdsa",
  "spki",
  "pkcs8",
  "der",
  "const-oid",
]

[dependencies]
crc32c = "0.6"
crc32fast = "1"
llrt_buffer = { version = "0.5.1-beta", path = "../llrt_buffer" }
llrt_context = { version = "0.5.1-beta", path = "../../libs/llrt_context" }
llrt_encoding = { version = "0.5.1-beta", path = "../../libs/llrt_encoding" }
llrt_utils = { version = "0.5.1-beta", path = "../../libs/llrt_utils", default-features = false }
llrt_json = { version = "0.5.1-beta", path = "../../libs/llrt_json", optional = true }
once_cell = "1"
rand = "0.8"
ring = { version = "0.17", features = ["std"] }
rquickjs = { git = "https://github.com/DelSkayn/rquickjs.git", version = "0.9.0", features = [
  "macro",
], default-features = false }
uuid = { version = "1", default-features = false, features = [
  "v4",
  "fast-rng",
] }
uuid-simd = "0.8"
aes = { version = "0.8", optional = true }
aes-gcm = { version = "0.10", optional = true }
aes-kw = { version = "0.2", features = ["alloc"], optional = true }
cbc = { version = "0.1", features = ["std"], optional = true }
ctr = { version = "0.9", optional = true }
rsa = { version = "0.9", features = [
  "std",
  "sha2",
], default-features = false, optional = true }
p256 = { version = "0.13", optional = true }
p384 = { version = "0.13", optional = true }
p521 = { version = "0.13", optional = true }
elliptic-curve = { version = "0.13", optional = true }
x25519-dalek = { version = "2", features = [
  "static_secrets",
  "zeroize",
  "getrandom",
], optional = true }
ecdsa = { version = "0.16", optional = true }
spki = { version = "0.7", features = ["std"], optional = true }
pkcs8 = { version = "0.10", features = ["std"], optional = true }
der = { version = "0.7", features = ["derive"], optional = true }
const-oid = { version = "0.9", features = ["db"], optional = true }

[target.'cfg(target_os = "windows")'.dependencies]
memchr = "2"
md-5 = "0.10"
[target.'cfg(not(target_os = "windows"))'.dependencies]
md-5 = { version = "0.10", features = ["asm"] }

[dev-dependencies]
llrt_test = { path = "../../helpers/llrt_test" }
tokio = { version = "1", features = ["full"] }
