[package]
name = "llrt_crypto"
description = "LLRT Module crypto"
version = "0.5.1-beta"
edition = "2021"
license = "Apache-2.0"
repository = "https://github.com/awslabs/llrt"
readme = "README.md"

[lib]
name = "llrt_crypto"
path = "src/lib.rs"

[features]
default = ["subtle-rs"]

subtle-rs = [
  "llrt_json",
  "aes",
  "aes-gcm",
  "aes-kw",
  "cbc",
  "ctr",
  "rsa",
  "p256",
  "p384",
  "p521",
  "elliptic-curve",
  "x25519-dalek",
  "ecdsa",
  "spki",
  "der",
  "const-oid",
]

[dependencies]
crc32c = { version = "0.6", default-features = false }
crc32fast = { version = "1", default-features = false }
llrt_buffer = { version = "0.5.1-beta", path = "../llrt_buffer" }
llrt_context = { version = "0.5.1-beta", path = "../../libs/llrt_context" }
llrt_encoding = { version = "0.5.1-beta", path = "../../libs/llrt_encoding" }
llrt_utils = { version = "0.5.1-beta", path = "../../libs/llrt_utils", default-features = false }
once_cell = { version = "1", features = [
  "std",
], default-features = false }
rand = { version = "0.8", features = [
  "std",
  "std_rng",
], default-features = false }
rquickjs = { git = "https://github.com/DelSkayn/rquickjs.git", version = "0.9.0", features = [
  "macro",
], default-features = false }
uuid = { version = "1", features = [
  "fast-rng",
  "v4",
], default-features = false }
uuid-simd = { version = "0.8", features = [
  "uuid",
], default-features = false }

# optional
llrt_json = { version = "0.5.1-beta", path = "../../libs/llrt_json", optional = true }
ring = { version = "0.17", default-features = false }
aes = { version = "0.8", optional = true }
aes-gcm = { version = "0.10", features = [
  "alloc",
], default-features = false, optional = true }
aes-kw = { version = "0.2", features = [
  "alloc",
], default-features = false, optional = true }
cbc = { version = "0.1", features = ["std"], optional = true }
ctr = { version = "0.9", default-features = false, optional = true }
rsa = { version = "0.9", features = [
  "std",
  "sha2",
], default-features = false, optional = true }
p256 = { version = "0.13", features = [
  "ecdh",
  "ecdsa",
  "pkcs8",
], default-features = false, optional = true }
p384 = { version = "0.13", features = [
  "ecdh",
  "ecdsa",
  "pkcs8",
], default-features = false, optional = true }
p521 = { version = "0.13", features = [
  "ecdh",
  "ecdsa",
  "pkcs8",
], default-features = false, optional = true }
elliptic-curve = { version = "0.13", features = [
  "alloc",
  "arithmetic",
], default-features = false, optional = true }
x25519-dalek = { version = "2", features = [
  "getrandom",
  "static_secrets",
  "zeroize",
], default-features = false, optional = true }
ecdsa = { version = "0.16", default-features = false, optional = true }
spki = { version = "0.7", features = [
  "alloc",
], default-features = false, optional = true }
der = { version = "0.7", features = [
  "derive",
], default-features = false, optional = true }
const-oid = { version = "0.9", features = [
  "db",
], default-features = false, optional = true }

[target.'cfg(target_os = "windows")'.dependencies]
memchr = { version = "2", default-features = false }
md-5 = { version = "0.10", default-features = false }

[target.'cfg(not(target_os = "windows"))'.dependencies]
md-5 = { version = "0.10", features = [
  "asm",
], default-features = false }

[dev-dependencies]
llrt_test = { path = "../../libs/llrt_test" }

