[package]
name = "llrt_crypto"
description = "LLRT Module crypto"
version = "0.3.0-beta"
edition = "2021"
license = "Apache-2.0"
repository = "https://github.com/awslabs/llrt"
readme = "README.md"

[lib]
name = "llrt_crypto"
path = "src/lib.rs"

[dependencies]
crc32c = "0.6"
crc32fast = "1"
llrt_buffer = { version = "0.3.0-beta", path = "../llrt_buffer" }
llrt_context = { version = "0.3.0-beta", path = "../../libs/llrt_context" }
llrt_encoding = { version = "0.3.0-beta", path = "../../libs/llrt_encoding" }
llrt_utils = { version = "0.3.0-beta", path = "../../libs/llrt_utils", default-features = false }
once_cell = "1"
rand = "0.8"
ring = { version = "0.17", features = ["std"] }
rquickjs = { git = "https://github.com/DelSkayn/rquickjs.git", version = "0.8.1", features = [
  "macro",
], default-features = false }
uuid = { version = "1", default-features = false, features = [
  "v4",
  "fast-rng",
] }
uuid-simd = "0.8"

aes = "0.8"
aes-gcm = "0.10"
cbc = { version = "0.1", features = ["std"] }
num-traits = "0.2"
rsa = { version = "0.9", features = ["std", "sha2"], default-features = false }
p256 = { version = "0.13", features = ["ecdh"] }
p384 = "0.13"
ctr = "0.9"

[target.'cfg(target_os = "windows")'.dependencies]
memchr = "2"
md-5 = "0.10"
[target.'cfg(not(target_os = "windows"))'.dependencies]
md-5 = { version = "0.10", features = ["asm"] }

[dev-dependencies]
llrt_test = { path = "../../libs/llrt_test" }
tokio = { version = "1", features = ["full"] }
