[package]
name = "llrt_path"
description = "LLRT Module path"
version = "0.7.0-beta"
edition = "2021"
license = "Apache-2.0"
repository = "https://github.com/awslabs/llrt"

[lib]
name = "llrt_path"
path = "src/lib.rs"

[dependencies]
llrt_utils = { version = "0.7.0-beta", path = "../../libs/llrt_utils", default-features = false }
rquickjs = { version = "0.11", features = [
  "std",
], default-features = false }

[target.'cfg(windows)'.dependencies]
memchr = { version = "2", default-features = false }

[dev-dependencies]
criterion = { version = "0.8", default-features = false }
once_cell = { version = "1", features = ["std"], default-features = false }
rand = { version = "0.10.0-rc.5", features = [
  "alloc",
  "thread_rng",
], default-features = false }

[[bench]]
name = "slash_replacement"
harness = false
