[package]
name = "llrt_path"
description = "LLRT Module path"
version = "0.5.1-beta"
edition = "2021"
license = "Apache-2.0"
repository = "https://github.com/awslabs/llrt"

[lib]
name = "llrt_path"
path = "src/lib.rs"

[dependencies]
llrt_utils = { version = "0.5.1-beta", path = "../../libs/llrt_utils", default-features = false }
rquickjs = { git = "https://github.com/DelSkayn/rquickjs.git", version = "0.9.0", default-features = false }

[target.'cfg(windows)'.dependencies]
memchr = "2"

[dev-dependencies]
criterion = "0.6"
once_cell = "1"
rand = "0.8"

[[bench]]
name = "slash_replacement"
harness = false
